<?php

/*
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Vehicle_geofence extends Base_Controller {

    function __construct() {
        parent::__construct();

        $this->load->model('alerts/mdl_alerts');
        $this->load->model('Mdl_vehicle_geofence');
    }

    /*
     * Listing of vehicle_geofence_assignment
     */

    function index() {
        $data['vehicle_geofence_assignment'] = $this->Mdl_vehicle_geofence->get_all_vehicle_geofence();

        $data['content_url'] = 'vehicle_geofence';
        $data['fa'] = 'fa fa-vehicle';
        $data['fa1'] = '';
        $data['fa2'] = '';
        $data['fa3'] = '';
        $data['fa4'] = '';
        $data['fa5'] = '';
        $data['title'] = 'HAWK | Vehicle Geofence';
        $data['content_title'] = 'Vehicle Geofence';
        $data['content_subtitle'] = 'Assign geofence and landmarks to vehicle';
        $data['content'] = 'vehicle_geofence/index.php';

        $this->load->view('main/main.php', $data);
    }

    /**
     * Load vehicle geofence view
     */
    function add_view() {
        $data['vehicle_data'] = $this->Mdl_vehicle_geofence->get_all_vehicles();
        $data['geofence_data'] = $this->Mdl_vehicle_geofence->get_all_geofences();
        $data['content_url'] = 'vehicle_geofence/add';
        $data['fa'] = 'fa fa-car';
        $data['fa1'] = '';
        $data['fa2'] = '';
        $data['fa3'] = '';
        $data['fa4'] = '';
        $data['fa5'] = '';
        $data['title'] = 'HAWK | Add Vehicle to Geofence';
        $data['content_title'] = 'Add Vehicle to Geofence';
        $data['content_subtitle'] = 'Add a Vehicle to Geofence/Landmark/Route';
        $data['content'] = 'vehicle_geofence/add.php';
        $this->load->view('main/main.php', $data);
    }

    function edit_view($id) {

        $data['vehicle_geofence_assignment'] = $this->Mdl_vehicle_geofence->get_vehicle_geofence_assignment($id);
        $data['content_url'] = 'vehicle_geofence/edit';
        $data['fa'] = 'fa fa-car';
        $data['fa1'] = '';
        $data['fa2'] = '';
        $data['fa3'] = '';
        $data['fa4'] = '';
        $data['fa5'] = '';
        $data['title'] = 'HAWK | Edit Geofence Alert Settings';
        $data['content_title'] = 'Edit Geofence Alert Settings';
        $data['content_subtitle'] = 'Edit Geofence Alert Settings for the Selected Vehicle';
        $data['content'] = 'vehicle_geofence/edit.php';
        $this->load->view('main/main.php', $data);
    }
    
    function view_details($id) {

        $data['vehicle_geofence_assignment'] = $this->Mdl_vehicle_geofence->get_vehicle_geofence_assignment($id);
        $data['content_url'] = 'vehicle_geofence/edit';
        $data['fa'] = 'fa fa-car';
        $data['fa1'] = '';
        $data['fa2'] = '';
        $data['fa3'] = '';
        $data['fa4'] = '';
        $data['fa5'] = '';
        $data['title'] = 'HAWK | Vehicle to Geofence Details';
        $data['content_title'] = 'Vehicle to Geofence Details';
        $data['content_subtitle'] = 'View a Vehicle to Geofence/Landmark Details.';
        $data['content'] = 'vehicle_geofence/view_details.php';
        $this->load->view('main/main.php', $data);
    }

        function fetch_view($id) {

        $data['vga'] = $this->Mdl_vehicle_geofence->get_vehicle_geofence_assignment($id);
        $data['content_url'] = 'vehicle_geofence/fetch_view';
        $data['fa'] = 'fa fa-car';
        $data['fa1'] = '';
        $data['fa2'] = '';
        $data['fa3'] = '';
        $data['fa4'] = '';
        $data['fa5'] = '';
        $data['title'] = 'HAWK | View Vehicle Assignments';
        $data['content_title'] = 'Vehicle Assignments';
        $data['content_subtitle'] = 'View Vehicle Assigned to Landmark or Geofence.';
        $data['content'] = 'vehicle_geofence/fetch_view.php';
        $this->load->view('main/main.php', $data);
    }

    /**
     * Function to create a new vehicle-(geofence/landmark) assignment 
     */
    function add_assignment() {
        $data = $this->input->post();
        
        if($this->Mdl_vehicle_geofence->check_duplicates($data["vehicle_id"],$data["geofence_id"])){
            echo "66";
            return;
        }
        
        /* if($this->Mdl_vehicle_geofence->has_active_geofence($data["vehicle_id"],$data["geofence_id"]) && $this->Mdl_vehicle_geofence->get_geofence_type($data['geofence_id']) =="geofence"){

            echo "77";
            return;
        } */
        
        /* if($this->Mdl_vehicle_geofence->has_active_route($data["vehicle_id"]) && $this->Mdl_vehicle_geofence->get_geofence_type($data['geofence_id']) =="route"){

            echo "88";
            return;
        } */
        
        echo $this->Mdl_vehicle_geofence->add_assignment($data);
    }

    function update_vehicle_geofence() {
// <<<<<<< HEAD
//         $data['in_alert'] = $this->input->post('in_alert');
//         $data['out_alert'] = $this->input->post('out_alert');
//         $data['sms_alert'] = $this->input->post('sms_alert');
//         $data['email_alert'] = $this->input->post('email_alert');
//         $data['status'] = $this->input->post('status');
           $id = $_POST['id'];
// =======
        $data['in_alert'] = $_POST['in_alert'];
        $data['out_alert'] = $_POST['out_alert'];
        $data['sms_alert'] = $_POST['sms_alert'];
        $data['email_alert'] = $_POST['email_alert'];
        $data['status'] = $_POST['status'];
		
		$geofence_id = $this->input->post("geofence_id");
		
       if($this->Mdl_vehicle_geofence->get_geofence_type($geofence_id) === "geofence" && $data['status'] == '1' && $this->Mdl_vehicle_geofence->has_active_geofence($this->input->post("vehicle_id"),$geofence_id)){
           echo "77";
           return;
       }
	   
	   if($this->Mdl_vehicle_geofence->get_geofence_type($geofence_id) == "route" && $data['status'] == '1' && $this->Mdl_vehicle_geofence->has_active_route($this->input->post("vehicle_id"),$geofence_id)){
           echo "66";
           return;
       }
	   /* echo $this->Mdl_vehicle_geofence->has_active_route($this->input->post("vehicle_id"));
	   exit; */
	   
       echo $this->Mdl_vehicle_geofence->update($data,$id);
    }
    
    /**
     * Function to check if the vehicle is currently attached to an active geofence.
     * @param type $vehicle_id
     */
//    function has_active_geofence($vehicle_id,$geofence_id){
//        return $this->Mdl_vehicle_geofence->has_active_geofence($vehicle_id,$geofence_id);
//    }

}
